# Build settings
markdown: kramdown
permalink: pretty


# Site settings
title: GDG DevFest Ukraine 2014
email: devfest@gdg.org.ua
description: "GDG DevFest - the biggest Google related event in Ukraine"
baseurl: ""
url: "http://devfest.gdg.org.ua/"
permalink: /blog/:title
googleAnalyticsTrackingId: "UA-43643469-1"
googleAnalyticsSiteUrl: "devfest.gdg.org.ua"

# Conference Locaion block
eventLocationName: "Kinopalace Cinema"
eventLocationAddress: "22 Teatral'na St, Lviv"
eventStartTime: "2014-10-24T09:00"
eventStartTimeHumanReadable: "9:00"
eventEndTime: "2014-10-25T20:00"
eventEndTimeHumanReadable: "20:00"
eventPlaceCoordinates: "49.843237,24.028751"
mapCenterCoordinates: "49.842537,24.025701"
mapMobileCenterCoordinates: "49.841620, 24.029411"

# Logistics Location Block
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"

# Subscribe
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"

# Documents
c4pUrl: "http://bit.ly/dfua-c4p"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@GDGLviv"
socialImageSrc: "/img/hero.jpg"

# Header
eventDate: "October 24-25, Lviv"
typeoutTextValues: '"", "Conference", "Workshops", "Hackathon", "Ukraine"'

# About Event Block
eventName: "GDG DevFest Ukraine"

# Team Block
aboutUs: Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences.

# Speakers List Block
showSessions: false
thumbnailsFolder: /img/speakers/

# Footer
gplusFollowUsUrl: "https://plus.google.com/b/102444623953913144164"
twitterFollowUsUrl: "https://twitter.com/intent/user?screen_name=GDGLviv"
fbFollowUsUrl: "https://facebook.com/GDGLviv"

# Blog
blogCommentsEnabled: true
discusShortName: "devfestua"