# Build settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site settings
title: GDG DevFest Ukraine 2014
email: devfest@gdg.org.ua
description: "October 24-25, Lviv, Ukraine. GDG DevFest - the biggest Google related event in Ukraine. 350+ attendees, 48 hours of pure Google content, 28+ speakers from Ukraine and beyond, 3 parallel tracks."
baseurl: ""
url: "http://devfest.gdg.org.ua"
permalink: /blog/:title
googleAnalyticsTrackingId: "UA-43643469-1"
googleAnalyticsSiteUrl: "devfest.gdg.org.ua"
siteVerification: "GxUE9cpxaP54b7Ymknz-fxWBiIUrJOqx1PZ5gkRHGeY"

# Organizer Info
organizerName: "GDG Lviv"
organizerAlternateName: "Google Developer Group Lviv"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "lviv@gdg.org.ua"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@GDGLviv"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.jpg"
socialImageSrcGooglePlusTwo: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.jpg"
socialImageSrcTwitterTwo: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.jpg"
socialImageSrcFacebookTwo: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_2014_Partnership_Proposition.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {permalink: "/#tickets", text: "Buy tickets"}
rightNavigationButtons:
 - {permalink: "/#tickets", text: "Buy tickets"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest <typeout> 2014"
eventDate: "October 24-25, Lviv"
typeoutTextValues: '"", "Conference", "Workshops", "Hackathon", "Ukraine"'
typeoutFallback: "Ukraine"
heroButtons:
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About GDG DevFest"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in Ukraine carefully crafted for you by GDG community! Awesome speakers and lot's of fun! This time, right in the heart of Lviv!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day free-style hackaton! Want some real teambuilding on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "28", specialCharacter: "+", info: "speakers", detail: "from Ukraine and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Kinopalace Cinema"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "22 Teatral'na St"
eventAddressLocality: "Lviv"
eventAddressLocalityRegion: "Lvivska"
eventPostalCode: "79000"
eventAddressCountry: "Ukraine"
eventStartTime: "2014-10-24T10:00"
eventDoorTime: "09:00"
eventEndTime: "2014-10-24T20:00"
eventPlaceCoordinates: "49.843237,24.028751"
mapCenterCoordinates: "49.842537,24.025701"
mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "lviv.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "dfua"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=1500"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
  soldOut: true
  soldOutText: "Sold Out"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund."
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
   - {link: "https://developers.google.com", text: "Google Developers"}
   - {link: "http://gdg-devfest-ua.appspot.com/", text: "GDG DevFest Ukraine 2013"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:devfest@gdg.org.ua", text: "devfest@gdg.org.ua"}
 -
  title: "Other"
  links:
   - {permalink: "/assets/GDG_DevFest_2014_Partnership_Proposition.pdf", text: "Partnership Proposition"}
   - {link: "http://bit.ly/dfua-media", text: "Media Kit"}
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"

# Logistics Direction Details Block
directionDetailsImage: "lviv-day.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
# directionDetailsWideCards: 
#  -
#   title: "Questions?"
#   subCards:
#    -
#     title: "Hotels"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    - 
#     title: "Registration"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Attendance Details"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Task"
hackathonRows:
 - {title: "", image: "hackathon.png", details: "Redesign existing app to Material Design. Youâ€™ll have 8 hours to implement redesigned UI for one of the proposed applications. No need to develop whole app, only UI with mock data."}

# Hackathon Technologies Block
hackathonTechnologiesTitle: "Technologies"
hackathonTechnologies:
 - {title: "Android L", image: "android-l.png"}
 - {title: "Web with Polymer, Angular Js and Dart", image: "web.png"}

# Hackathon FAQ Block
hackathonFaqTitle: "FAQ"
hackathonFaqList:
 - {item: "Registration is free but at least one team member should have conference ticket"}
 - {item: "Apps proposed for redesign will be announced on the hackathon"}
 - {item: "Max team size: 3 people"}
 - {item: "Pitch duration: 360 seconds"}
 - {item: "Demo duration: 360 seconds"}
 - {item: "You have to bring your own laptop"}
 - {item: "Winners are selected by independent jouri"}
 - {item: "Winners will be announced on Saturday during GDG Awards"}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "ComeIn"
hackathonLocationLink: "http://www.comein.lviv.ua/"
hackathonStreetAddress: "Solomii Krushel'nyts'koi St, 3"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through:"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-24T19:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.838144, 24.022544"
hackathonMapCenterCoordinates: "49.837805, 24.020693"
hackathonMapMobileCenterCoordinates: "49.838779, 24.022341"